//===- KtdpDialect.hpp - KTDP dialect public header -------*- C++ -*-===//
//
//===----------------------------------------------------------------------===//
#ifndef KTDP_KTDPDIALECT_HPP_
#define KTDP_KTDPDIALECT_HPP_

#include "mlir/IR/Dialect.h"

// Generated by mlir-tblgen --gen-dialect-decls -dialect=ktdp
#include "Ktdp/KtdpDialect.hpp.inc"

#endif // KTDP_KTDPDIALECT_HPP_
